// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.24;

// GENERATED by scripts/fixture/build-fixture-witness.mjs — do not edit by hand.
// Witness bundle: test-vectors/sepolia-fixture-v1.json
library FixtureData {
    bytes32 internal constant SPACE_SALT = 0xfb9f388564b91414d11ad44e1a3c1e78e71b75d869ce180c7dc762de5412c514;
    address internal constant CONTROLLER = 0x3d0ab53241A2913D7939ae02f7083169fE7b823B;
    bytes32 internal constant SPACE_ID = 0xfbe20b841e2cb8d5e8094da6a9be9ebe19bb4d52c6155f465b40aa7bf1c13564;

    // transition 1
    bytes32 internal constant DELTA_COMMITMENT_1 = 0x7311f5e6b1c64cc5f3f16c77b471ce5d53f8090d3e20b056efb0f1922085266e;
    bytes32 internal constant PROVENANCE_COMMITMENT_1 = 0x0000000000000000000000000000000000000000000000000000000000000000;
    bytes32 internal constant PROFILE_ID_1 = 0xac4a313d81b72c5de24109f69fd82139cf5b3df04391fb8e40ad8fde817ed1be;
    bytes32 internal constant LOCATOR_COMMITMENT_1 = 0x0000000000000000000000000000000000000000000000000000000000000000;
    bytes32 internal constant EXPECTED_TRANSITION_ID_1 = 0x4a7cdcd9477eec11645a43afc83d7f007018af4b3648e33eaffcf951a1e156b0;
    bytes32 internal constant EXPECTED_NEXT_ROOT_1 = 0x712d4e806ac862e95c89062e2d70b9231dc9f11cb0624ffb2970579c6b81832c;

    // transition 2
    bytes32 internal constant DELTA_COMMITMENT_2 = 0x4cee6ec6ac48784bbc0a91b9ef43b6b2e98b887f60f6b3908fad8f1131a54aa7;
    bytes32 internal constant PROVENANCE_COMMITMENT_2 = 0xeb52e8e86ea7127050d357f99d6fa68962bde393161cc263dbfa10dd35830e23;
    bytes32 internal constant PROFILE_ID_2 = 0xd9670376cf3ba57abb92989eeb0ff8a76d48666287a9091171d3c9bc9d5af434;
    bytes32 internal constant LOCATOR_COMMITMENT_2 = 0x0000000000000000000000000000000000000000000000000000000000000000;
    bytes32 internal constant EXPECTED_TRANSITION_ID_2 = 0x689d8185a18fb91508cb22877d973daac40e2cf9b3d1029acd2383384faaec3e;
    bytes32 internal constant EXPECTED_NEXT_ROOT_2 = 0x0c1a5ae06be06e09cca58a64cced93a0bad36fb34aa09c90092910c9bd026bb5;

    // transition 3
    bytes32 internal constant DELTA_COMMITMENT_3 = 0x908827979c87f807d2dfe85e566a809f8eeae2534b9f21de2142b71c5841fc46;
    bytes32 internal constant PROVENANCE_COMMITMENT_3 = 0x9b763e9fdfa94d4c209583a477eca7445950fe950a3c2770957f800c082fb9c3;
    bytes32 internal constant PROFILE_ID_3 = 0xf847003f2b63074f71c873268d340107107939eb218235cf88ed46caa0905f45;
    bytes32 internal constant LOCATOR_COMMITMENT_3 = 0x0000000000000000000000000000000000000000000000000000000000000000;
    bytes32 internal constant EXPECTED_TRANSITION_ID_3 = 0xeb0464abe6037dfe997c48b2dbe316e5bd96bfe80f6b14a08ebd57cdd3b8abe4;
    bytes32 internal constant EXPECTED_NEXT_ROOT_3 = 0x8d7362e62f75ff4fbc9047b6881e42f933de9dd7af0fbad228e8f4228b50bec7;

    // transition 4
    bytes32 internal constant DELTA_COMMITMENT_4 = 0x4b21b472936a3e89b1031305bb061705bebdaa7aadecfda134058ac2d973a407;
    bytes32 internal constant PROVENANCE_COMMITMENT_4 = 0xdb4fb5039bfeece75342d413b8b80ab7c48723bae4838fd1c1e35b6bc505b1d9;
    bytes32 internal constant PROFILE_ID_4 = 0xac4a313d81b72c5de24109f69fd82139cf5b3df04391fb8e40ad8fde817ed1be;
    bytes32 internal constant LOCATOR_COMMITMENT_4 = 0x2065a4e163948b2408a7cae309a55e1359591ac2f251c488943b40a28951de70;
    bytes32 internal constant EXPECTED_TRANSITION_ID_4 = 0x154c1e643dfec801e4e227f52ae24147a1cca0260533d258916c07337c2bd09d;
    bytes32 internal constant EXPECTED_NEXT_ROOT_4 = 0x280889644f1f2748a27bb973df0c1efde465ae2a1334e705f7cb4c7a72ad5bc0;
}
